[build]
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "config.settings" }